repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-ast
  - id: check-toml
  - id: sort-simple-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/python/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
  - id: flake8
    additional_dependencies: ["flake8-bugbear==21.4.3"]
